### PR TITLE
Add shared runtime branch

### PR DESCRIPTION
**Pull request by arttarawork**

### CODE REVIEW

**Comment by arttarawork** [comment]
Recent tests have not been showing up the previously discussed #N/A issue, so I'm setting up a draft PR to run it through our pipeline.

**Comment by arttarawork** [comment]
Still the same #N/A issue

**Comment by TCourtneyOwen** [comment]
It's been awhile since I looked at this, but I recall it works on my machine and not on yours for some reason. I need to revisit this

**Comment by TCourtneyOwen** [comment]
@arttarawork yes I just confirmed that the JS template works on my machine with the exception of the taskpane being grayed out, which is a new issue that appears in the typescript template as well (I mentioned this in our DevX channel yesterday)

**Comment by arttarawork** [comment]
> It's been awhile since I looked at this, but I recall it works on my machine and not on yours for some reason. I need to revisit this

To make things easy, the build finally works on my laptop, but fails in the pipeline 😂

**Review by TCourtneyOwen — COMMENTED** [review]
You shouldn't delete this. When you merge, just do "git reset package-lock.json" to remove that from the merge, delete package-lock.json and then do npm install to regnerate and then check in the regnerated package-lock.json with the merge commit

**Comment by akrantz** [comment]
Do you really want to merge this to the master branch? I thought shared runtime should be a separate branch.

**Review by TCourtneyOwen — APPROVED** [review]

**Pull request closed without merging**
